name: flutter_facebook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/person-circle.svg
    - assets/images/icons/round-bell.svg
    - assets/images/user_avatar.jpg
    - assets/images/rec_user_photo.jpg
    - assets/images/landscape.jpg
    - assets/images/massif.jpg
    - assets/images/mountain.jpg
    - assets/images/thumb_up.jpg